services:
  - type: web
    name: solana-server
    env: rust
    buildCommand: "cargo build --release"
    startCommand: "cargo run --release"
    envVars:
      - key: RUST_LOG
        value: info
    plan: free
